import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Toaster from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => (
  <header className="sticky top-0 z-40 bg-red-200">
    <div className="h-16 grid grid-cols-5 px-8">
      <Link href="/">logo</Link>
      <nav className="col-span-4 flex justify-end items-center">
        <a className="ml-8 font-bold hover:underline" href="#benefits">
          Benefits
        </a>
        <a className="ml-8 font-bold hover:underline" href="#guide">
          Guide
        </a>
        <a className="ml-8 font-bold hover:underline" href="#feedback">
          Feedback
        </a>
        <a className="ml-8 font-bold hover:underline" href="#cta">
          Sign up
        </a>
        <a className="ml-8 font-bold hover:underline" href="#plans">
          Plans
        </a>
        <a className="ml-8 font-bold hover:underline" href="#faq">
          FAQ
        </a>
        <a className="ml-8 font-bold hover:underline" href="#support">
          Support
        </a>
        <span className="ml-8 font-bold opacity-30 cursor-not-allowed">
          Profile/Dashboard
        </span>
      </nav>
    </div>
  </header>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
