import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Toaster from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => (
  <header className="sticky top-0 z-40 h-16 bg-red-200">
    <Link href="/">logo</Link>
  </header>
);
const Footer = () => (
  // <footer className="sticky bottom-0 z-40 h-16 bg-red-200">
  <footer className="h-16 bg-red-200">
    <Link href="/">footer</Link>
  </footer>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container border-2 border-black relative py-8">
          {children}
        </main>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}
